#!/bin/bash

#Download ptools and make it a term command:
wget https://raw.githubusercontent.com/givinghawk/PTools/main/ptools.sh
sudo cp ptools.sh /usr/local/bin/ptools
sudo chmod +x /usr/local/bin/ptools
echo "Done!"
